local LootTable = {
	{ item = "Golden Apple", chance = 0.05, unique = true }, -- Legendary drop
	{ item = "Green Apple", chance = 0.1, unique = false },
	{ item = "Heavy Iron Axe", chance = 0.02, unique = false },
	{ item = "Iron Sword", chance = 0.15, unique = false },
	{ item = "Red Apple", chance = 0.2, unique = false },
	{ item = "Silver Sword", chance = 0.08, unique = false },
	{ item = "Stormcarver", chance = 0.01, unique = false },
	{ item = "Torch", chance = 0.25, unique = false },
	{ item = "Wood", chance = 0.4, unique = false },
}

return LootTable
