	local NorsegodsInfo = {
	Helgi = {
		icon = "rbxassetid://117676066570499",
		description = "Helgi: Grants a boost to stamina regeneration.",
		rarity = "Common"
	},
	Eir = {
		icon = "rbxassetid://119946556579083",
		description = "Eir: Enhances healing effects and reduces incoming damage.",
		rarity = "Common"
	},
	Modi = {
		icon = "rbxassetid://103996237804295",
		description = "Modi: Increases physical attack power.",
		rarity = "Common"
	},
	Njord = {
		icon = "rbxassetid://92624122952757",
		description = "Njord: Boosts movement speed.",
		rarity = "Uncommon"
	},
	Forseti = {
		icon = "rbxassetid://124283407912916",
		description = "Forseti: Reduces cooldowns for defensive abilities.",
		rarity = "Uncommon"
	},
	Sif = {
		icon = "rbxassetid://118659824803383",
		description = "Sif: Increases damage for elemental and nature-based attacks.",
		rarity = "Uncommon"
	},
	Tyr = {
		icon = "rbxassetid://92259126006204",
		description = "Tyr: Grants a chance to ignore damage and reflect a portion back.",
		rarity = "Rare"
	},
	Freyr = {
		icon = "rbxassetid://133053510006169",
		description = "Freyr: Grants passive healing in sunlight.",
		rarity = "Rare"
	},
	Skadi = {
		icon = "rbxassetid://126895947930191",
		description = "Skadi: Enhances mobility in snowy areas and increases attack damage against animals.",
		rarity = "Rare"
	},
	Thor = {
		icon = "rbxassetid://135915831110229",
		description = "Thor: Grants a chance to electrocute the enemy when physically attacking them.",
		rarity = "Epic"
	},
	Freyja = {
		icon = "rbxassetid://82772954784493",
		description = "Freyja: Increases critical hit chances.",
		rarity = "Epic"
	},
	Heimdall = {
		icon = "rbxassetid://107695052725600",
		description = "Heimdall: Improves perception and reveals hidden enemies.",
		rarity = "Epic"
	},
	Odin = {
		icon = "rbxassetid://111794141303617",
		description = "Odin: Increase overall strength and all types of damage.",
		rarity = "Legendary"
	},
	Loki = {
		icon = "rbxassetid://130568284787009",
		description = "Loki: Increases evasion and critical damage while causing confusion to enemies.",
		rarity = "Legendary"
	},
	Fenrir = {
		icon = "rbxassetid://129396483492405",
		description = "Fenrir: Enhances physical damage when low HP and grants lifesteal abilities.",
		rarity = "Legendary"
	},
}

return NorsegodsInfo
