local Cooking = {
	Newcomer = {
		"Grilled Cod",
		"Smoked Mullet",
		"Root Soup",
		"Fried Pompano",
		"Cooked Meat"
	},

	Novice = {
		"Herb-Grilled Fish",
		"Boar Stew",
		"Egg & Meat Skewer",
		"Charcoal Stew",
		"Yarrow Extract",
	},

	Skilled = {
		"Fish Stew",
		"Blue Fish Skewer",
		"Berry Tart",
		"Wild Forest Bread",
		"Spiced Berry Stew",
		"Clover Pie",
		"Bitter Moss Tonic",
		"Mead Tonic",
	},

	Veteran = {
		"Golden Pompano Delight",
		"Honey Cake",
		"Frostberry Sorbet",
		"Healing Cod Broth",
		"Icy Root Brew",
	},

	Elite = {
		"Golden Jam",
		"Frostleaf Elixir",
	},
}

return Cooking
