local Markets = {
	["Leifrik"] = {
		Items = {
			"Red Apple",
			"Green Apple",
			"Golden Apple",
			"Boar Flesh",
			"Boar Skin",
			--"Boar Tusk",
			--"Boar Steak",
		},
	},
	["Haldor"] = {
		Items = {
			"Heavy Iron Axe",
			"Iron Sword",
			--"Iron Shield",
			--"Iron Helmet",
			--"Iron Armor",
			--"Iron Boots",
			--"Iron Hammer",
		},
	},
	["Alfrun"] = {
		Items = { 
			"Torch", 
			"Lantern",
			--"Wooden Shield",
		},
	},
}

return Markets
